### ISSUE TITLE
Random(?) failures in ParseGeneratedDocTest

### ISSUE THREAD

**Issue by roblg** [johnynek/bazel-deps#132]
I just had `ParseGeneratedDocTest` fail once with the following error, then succeed on the next run with no changes:

```
ParseGeneratedDocTest:
- parse randomly generated Model.toDoc (43 seconds, 546 milliseconds)
- Dependencies.normalize laws *** FAILED *** (180 milliseconds)
  UnsupportedOperationException was thrown during property evaluation.
    Message: empty.minBy
    Occurred when passed generated values (
      arg0 = List((ArtifactOrProject(l),ProjectRecord(Java,Some(Version(196)),None,Some(Set((MavenGroup(t8dxqtemaRjtafjhwY53jwdaspvsBlxnvfrgtuy9),ArtifactOrProject(iPnfSxj85g2exnsox3oxNyisdx1)), (MavenGroup(xhlqkwdapamruWdkjtubvkntuiLcpvdyroxAtuvvrimScz5rzhhveyjoh),ArtifactOrProject(bBTaYvdrslkYkcutawkteercrullblakj2idtcb0rknkbe)))),Some(Set((MavenGroup(hySadgppw3nyduddhjxbgw8w3uANUtplzjzro5f71ptwlvbwmmkvardogque),ArtifactOrProject(mhTkxUqgp1kxcs4e72ktt0bwFtvktlngla3vuyg9eVSesi)), (MavenGroup(vgut02xezxIm5jg3nhaQzyxdtoutsjnqzgkAbyxbpbzfvj7hfcml),ArtifactOrProject(pmdiff5khwrrlndeo2ezdhoxh8c70ffcqxAo)))),Some(Set()))), (ArtifactOrProject(l),ProjectRecord(Java,None,None,None,Some(Set()),None))) // 8 shrinks
    )
  org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException:
  at org.scalatest.enablers.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:223)
  at org.scalatest.enablers.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:219)
  at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:140)
  at org.scalatest.prop.GeneratorDrivenPropertyChecks$class.forAll(GeneratorDrivenPropertyChecks.scala:944)
  at org.scalatest.prop.PropertyChecks$.forAll(PropertyChecks.scala:107)
  at com.github.johnynek.bazel_deps.ParseGeneratedDocTest$$anonfun$2.apply(ParseGeneratedDocTest.scala:21)
  at com.github.johnynek.bazel_deps.ParseGeneratedDocTest$$anonfun$2.apply(ParseGeneratedDocTest.scala:17)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at org.scalatest.FunSuite.run(FunSuite.scala:1560)
  at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1210)
  at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1257)
  at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1255)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1255)
  at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
  at org.scalatest.Suite$class.run(Suite.scala:1144)
  at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
  at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
  at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
  at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
  at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
  at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
  at org.scalatest.tools.Runner$.main(Runner.scala:827)
  at org.scalatest.tools.Runner.main(Runner.scala)
  at io.bazel.rulesscala.scala_test.Runner.main(Runner.java:19)
  Cause: java.lang.UnsupportedOperationException: empty.minBy
  at scala.collection.TraversableOnce$class.minBy(TraversableOnce.scala:254)
  at scala.collection.AbstractTraversable.minBy(Traversable.scala:104)
  at com.github.johnynek.bazel_deps.Dependencies$.com$github$johnynek$bazel_deps$Dependencies$$select$1(DepsModel.scala:714)
  at com.github.johnynek.bazel_deps.Dependencies$$anonfun$normalize$1.apply(DepsModel.scala:750)
  at com.github.johnynek.bazel_deps.Dependencies$$anonfun$normalize$1.apply(DepsModel.scala:749)
  at scala.collection.immutable.List.flatMap(List.scala:338)
  at com.github.johnynek.bazel_deps.Dependencies$.normalize(DepsModel.scala:749)
  at com.github.johnynek.bazel_deps.ParseGeneratedDocTest$$anonfun$2$$anonfun$apply$2.apply(ParseGeneratedDocTest.scala:22)
  at com.github.johnynek.bazel_deps.ParseGeneratedDocTest$$anonfun$2$$anonfun$apply$2.apply(ParseGeneratedDocTest.scala:21)
  at org.scalatest.prop.GeneratorDrivenPropertyChecks$$anonfun$32.liftedTree9$1(GeneratorDrivenPropertyChecks.scala:931)
  at org.scalatest.prop.GeneratorDrivenPropertyChecks$$anonfun$32.apply(GeneratorDrivenPropertyChecks.scala:930)
  at org.scalatest.prop.GeneratorDrivenPropertyChecks$$anonfun$32.apply(GeneratorDrivenPropertyChecks.scala:928)
  at org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:712)
  at org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$3.apply(Prop.scala:712)
  at org.scalacheck.Prop$.secure(Prop.scala:456)
  at org.scalacheck.Prop$$anonfun$forAllShrink$1.org$scalacheck$Prop$$anonfun$$result$1(Prop.scala:712)
  at org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$4.apply(Prop.scala:719)
  at org.scalacheck.Prop$$anonfun$forAllShrink$1$$anonfun$4.apply(Prop.scala:719)
  at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
  at scala.collection.immutable.Stream$$anonfun$map$1.apply(Stream.scala:418)
  at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1233)
  at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1223)
  at scala.collection.immutable.Stream.dropWhile(Stream.scala:963)
  at org.scalacheck.Prop$$anonfun$forAllShrink$1.getFirstFailure$1(Prop.scala:720)
  at org.scalacheck.Prop$$anonfun$forAllShrink$1.shrinker$1(Prop.scala:729)
  at org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:751)
  at org.scalacheck.Prop$$anonfun$forAllShrink$1.apply(Prop.scala:706)
  at org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:292)
  at org.scalacheck.Prop$$anonfun$apply$5.apply(Prop.scala:291)
  at org.scalacheck.PropFromFun.apply(Prop.scala:22)
  at org.scalacheck.Test$.org$scalacheck$Test$$workerFun$1(Test.scala:294)
  at org.scalacheck.Test$$anonfun$3.apply(Test.scala:323)
  at org.scalacheck.Test$$anonfun$3.apply(Test.scala:323)
  at org.scalacheck.Platform$.runWorkers(Platform.scala:40)
  at org.scalacheck.Test$.check(Test.scala:323)
  at org.scalatest.enablers.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:88)
  at org.scalatest.prop.GeneratorDrivenPropertyChecks$class.forAll(GeneratorDrivenPropertyChecks.scala:944)
  at org.scalatest.prop.PropertyChecks$.forAll(PropertyChecks.scala:107)
  at com.github.johnynek.bazel_deps.ParseGeneratedDocTest$$anonfun$2.apply(ParseGeneratedDocTest.scala:21)
  at com.github.johnynek.bazel_deps.ParseGeneratedDocTest$$anonfun$2.apply(ParseGeneratedDocTest.scala:17)
  at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
  at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
  at org.scalatest.Transformer.apply(Transformer.scala:22)
  at org.scalatest.Transformer.apply(Transformer.scala:20)
  at org.scalatest.FunSuiteLike$$anon$1.apply(FunSuiteLike.scala:186)
  at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
  at org.scalatest.FunSuite.withFixture(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$class.invokeWithFixture$1(FunSuiteLike.scala:183)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.FunSuiteLike$$anonfun$runTest$1.apply(FunSuiteLike.scala:196)
  at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
  at org.scalatest.FunSuiteLike$class.runTest(FunSuiteLike.scala:196)
  at org.scalatest.FunSuite.runTest(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.FunSuiteLike$$anonfun$runTests$1.apply(FunSuiteLike.scala:229)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
  at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
  at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
  at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
  at org.scalatest.FunSuiteLike$class.runTests(FunSuiteLike.scala:229)
  at org.scalatest.FunSuite.runTests(FunSuite.scala:1560)
  at org.scalatest.Suite$class.run(Suite.scala:1147)
  at org.scalatest.FunSuite.org$scalatest$FunSuiteLike$$super$run(FunSuite.scala:1560)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.FunSuiteLike$$anonfun$run$1.apply(FunSuiteLike.scala:233)
  at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
  at org.scalatest.FunSuiteLike$class.run(FunSuiteLike.scala:233)
  at org.scalatest.FunSuite.run(FunSuite.scala:1560)
  at org.scalatest.Suite$class.callExecuteOnSuite$1(Suite.scala:1210)
  at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1257)
  at org.scalatest.Suite$$anonfun$runNestedSuites$1.apply(Suite.scala:1255)
  at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
  at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:186)
  at org.scalatest.Suite$class.runNestedSuites(Suite.scala:1255)
  at org.scalatest.tools.DiscoverySuite.runNestedSuites(DiscoverySuite.scala:30)
  at org.scalatest.Suite$class.run(Suite.scala:1144)
  at org.scalatest.tools.DiscoverySuite.run(DiscoverySuite.scala:30)
  at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
  at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
  at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
  at scala.collection.immutable.List.foreach(List.scala:392)
  at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
  at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)

**Comment by johnynek** [comment]
This is a real failure in the property check. So either there is a real bug somewhere or the test is buggy.

It gives the input that causes the law to fail. I’ll try to reproduce it.
