### ISSUE TITLE
Fails to resolve pom package dependencies.

### ISSUE THREAD

**Issue by aherrmann** [johnynek/bazel-deps#208]
bazel-deps fails on dependencies that are pom packages, because it tries to download non-existing jar files to compute the sha1 hash. E.g. [org.monodb:casbah_2.12.0-RC1](https://repo.maven.apache.org/maven2/org/mongodb/casbah_2.12.0-RC1/3.1.1/). The following test-case demonstrates this for a direct dependency with the coursier resolver. Indirect dependencies also cause a failure. The aether resolver fails as well.

``` diff
diff --git a/test/scala/com/github/johnynek/bazel_deps/CoursierTest.scala b/test/scala/com/github/johnynek/bazel_deps/CoursierTest.scala
index 54ce5ec..f05eff2 100644
--- a/test/scala/com/github/johnynek/bazel_deps/CoursierTest.scala
+++ b/test/scala/com/github/johnynek/bazel_deps/CoursierTest.scala
@@ -130,6 +130,40 @@ dependencies:
     assert(nonJarNodes.size == 0)
   }

+  test("test direct pom package dependency example") {
+    val config = """
+options:
+  buildHeader: [ "load(\"@io_bazel_rules_scala//scala:scala_import.bzl\", \"scala_import\")" ]
+  languages: [ "java", "scala:2.11.8" ]
+  resolverType: "coursier"
+  resolvers:
+    - id: "mavencentral"
+      type: "default"
+      url: https://repo.maven.apache.org/maven2/
+  transitivity: runtime_deps
+  versionConflictPolicy: highest
+dependencies:
+  org.mongodb:
+    casbah_2.12.0-RC1:
+      lang: java
+      version: "3.1.1"
+"""
+
+    val model = Decoders.decodeModel(Yaml, config).right.get
+    val (graph, shas, normalized) = MakeDeps.runResolve(model, null).get
+
+    assert(graph.nodes.contains(
+      MavenCoordinate(
+        MavenGroup("org.mongodb"), MavenArtifactId("casbah_2.12.0-RC1"), Version("3.1.1"))))
+
+    // make sure no non-jar packaging shows up, until bazel-deps can handle setting those
+    // as data dependencies
+    val nonJarNodes = graph.nodes
+      .filter { mc => mc.artifact.packaging != "jar" }
+
+    assert(nonJarNodes.size == 0)
+  }
+
   test("test jar packaging w/ classifier exclude example") {
     val config =
       """
```

The error message reads

```
- test direct pom package dependency example *** FAILED *** (1 second, 216 milliseconds)
  java.lang.RuntimeException: we could not download the artifact org.mongodb:casbah_2.12.0-RC1:3.1.1 to compute the hash for digest type Sha1 with error com.github.johnynek.bazel_deps.CoursierResolver$FileErrorException: not found: https://repo.maven.apache.org/maven2/org/mongodb/casbah_2.12.0-RC1/3.1.1/casbah_2.12.0-RC1-3.1.1.jar
  at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$3.apply(CoursierResolver.scala:116)
  at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$3.apply(CoursierResolver.scala:115)
  at com.github.johnynek.bazel_deps.CoursierResolver$$anon$1$$anonfun$handleErrorWith$1$$anonfun$apply$1.apply(CoursierResolver.scala:60)
  at com.github.johnynek.bazel_deps.CoursierResolver$$anon$1$$anonfun$handleErrorWith$1$$anonfun$apply$1.apply(CoursierResolver.scala:60)
  at cats.instances.FutureInstances$$anon$1$$anonfun$handleErrorWith$1.applyOrElse(future.scala:15)
  at cats.instances.FutureInstances$$anon$1$$anonfun$handleErrorWith$1.applyOrElse(future.scala:15)
  at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
  at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
  at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
  at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
  at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
  at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
  at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
  at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

cc @gdeest

**Comment by johnynek** [comment]
We have some work on supporting different packaging #119 . I think this should probably be related to that.

Can you possibly use a replacements rule to work around the issue?

Lastly, is this a coursier issue? Can you replicate the failure with the coursier CLI?
https://github.com/coursier/coursier

**Comment by aherrmann** [comment]
> Can you possibly use a replacements rule to work around the issue?

Likely yes.

> Lastly, is this a coursier issue? Can you replicate the failure with the coursier CLI?

It seems to be. Launch, fetch, and resolve all fail with the same error:

```
$ coursier launch org.monodb:casbah_2.12.0-RC1:3.1.1
$ coursier fetch org.monodb:casbah_2.12.0-RC1:3.1.1
$ coursier resolve org.monodb:casbah_2.12.0-RC1:3.1.1
Error:
  org.monodb:casbah_2.12.0-RC1:3.1.1
    not found: /home/me/.ivy2/local/org.monodb/casbah_2.12.0-RC1/3.1.1/ivys/ivy.xml
    not found: https://repo1.maven.org/maven2/org/monodb/casbah_2.12.0-RC1/3.1.1/casbah_2.12.0-RC1-3.1.1.pom
```

**Comment by johnynek** [comment]
Thanks for checking. Could you file a coursier issue and link to this issue. That project is fairly active so hopefully they can solve it at that level.

**Comment by aherrmann** [comment]
Sorry, I had a typo in the `coursier` cli commands. These work when the typo is fixed.

```
$ coursier launch org.mongodb:casbah_2.12.0-RC1:3.1.1
$ coursier fetch org.mongodb:casbah_2.12.0-RC1:3.1.1
$ coursier resolve org.mongodb:casbah_2.12.0-RC1:3.1.1
```

All succeed.

**Comment by simonyun** [comment]
Hi @aherrmann or @johnynek,

I'm trying to add http://central.maven.org/maven2/ca/uhn/hapi/fhir/hapi-fhir/3.6.0/ as a dependency and I think I'm running into this pom issue.

```
[main] ERROR MakeDeps - resolution and sha collection failed
java.lang.RuntimeException: we could not download the artifact ca.uhn.hapi.fhir:hapi-fhir:3.6.0 to compute the hash for digest type Sha1 with error com.github.johnynek.bazel_deps.CoursierResolver$FileErrorException: not found: http://central.maven.org/maven2/ca/uhn/hapi/fhir/hapi-fhir/3.6.0/hapi-fhir-3.6.0.jar
	at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$3.apply(CoursierResolver.scala:112)
	at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$3.apply(CoursierResolver.scala:111)
	at com.github.johnynek.bazel_deps.CoursierResolver$$anon$1$$anonfun$handleErrorWith$1$$anonfun$apply$1.apply(CoursierResolver.scala:53)
	at com.github.johnynek.bazel_deps.CoursierResolver$$anon$1$$anonfun$handleErrorWith$1$$anonfun$apply$1.apply(CoursierResolver.scala:53)
	at cats.instances.FutureInstances$$anon$1$$anonfun$handleErrorWith$1.applyOrElse(future.scala:15)
	at cats.instances.FutureInstances$$anon$1$$anonfun$handleErrorWith$1.applyOrElse(future.scala:15)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

What should the replacements rule look like for this pom? I'm not sure if the examples in the `README` and project would apply here.

Sorry for the dumb q — I'm new to the project and figure someone else might benefit from an example documented here.

Thanks!

**Comment by aherrmann** [comment]
I've tested this with https://github.com/johnynek/bazel-deps/pull/229 and the issue is resolved.
