### ISSUE TITLE
Pom Download Issue with Coursier

### ISSUE THREAD

**Issue by richwhitjr** [johnynek/bazel-deps#220]
I saw #208 which looks very close to the issue I am having although the end result of that seemed to be a typo.

My current problem is I see the following error when trying to depend on hive-exec 2.3.3.

```bash
java.lang.RuntimeException: no artifacts for org.apache.curator:apache-curator:pom:2.7.1 found
	at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$com$github$johnynek$bazel_deps$CoursierResolver$$lookup$1$1$$anonfun$apply$7$$anonfun$apply$9.apply(CoursierResolver.scala:188)
	at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$com$github$johnynek$bazel_deps$CoursierResolver$$lookup$1$1$$anonfun$apply$7$$anonfun$apply$9.apply(CoursierResolver.scala:186)
	at coursier.util.Task$$anonfun$flatMap$extension$1$$anonfun$apply$1.apply(Task.scala:10)
	at coursier.util.Task$$anonfun$flatMap$extension$1$$anonfun$apply$1.apply(Task.scala:10)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
	at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
ERROR: Non-zero return code '1' from command: Process exited with status 1
```

My maven-dependency.yaml looks something like:

```yaml
options:
  languages: [ "java", "scala:2.11.8" ]
  resolverType: "coursier"
  resolvers:
    - id: "mavencentral"
      type: "default"
      url: https://repo.maven.apache.org/maven2/
  strictVisibility: false
  transitivity: runtime_deps
  versionConflictPolicy: highest
  thirdPartyDirectory: third_party/jvm
dependencies:
    org.apache.hive:
    hive:
      lang: java
      version: "2.3.3"
      modules: [metastore, exec]
```

I am currently using version `d42fb3ba45c94c3398abdcfd762313d0b8784aec`.

The odd thing also is that coursier is able to download that same pom from it's CLI:

```bash
coursier fetch  org.apache.hive:hive-exec:2.3.3
```

Adding a direct depedency on apache-curator also doesn't help since coursier fails to find the jar instead of looking for the pom.  Didn't see an option i bazel-deps to add a pom dependency to help in that regard.

**Comment by johnynek** [comment]
Not #215 has some warnings about import scope handling. I think we need to see how coursier handles this in their tool and implement that.

I'm sorry the tool does not currently support this case.

**Comment by thundergolfer** [comment]
I just had this same issue with `org.apache.common:common-io:1.3.2`: 

```
java.lang.RuntimeException: no artifacts for org.apache.commons:commons-io:1.3.2 found
```

**Comment by johnynek** [comment]
Thanks!

This is the problem with using yaml rather than a format we control: parse errors are a bit harder to catch.

**Comment by thundergolfer** [comment]
@johnynek Would you be able to drop into this issue and include what you think is the best workaround for this problem?

**Comment by johnynek** [comment]
I would try the aether resolver as a work around.

I have seen a few cases where artifacts depend on poms that point to set of other jars. I think we don’t handle those cases correctly.

I really haven’t dug into why these cases don’t work. I’m sorry I don’t have much bandwidth to debug cases right now.

I would inspect the transitive pom graph and see what is different about these cases. I imagine something would pop out. I also expect there is some rare case or cases that require special handling that we aren’t handling correctly currently.
