### ISSUE TITLE
Missing unversioned deps in the normalized graph

### ISSUE THREAD

**Issue by Globegitter** [johnynek/bazel-deps#221]
I am trying to download `logback-classic` and getting the following error:

```
[main] ERROR MakeDeps - resolution and sha collection failed
java.lang.Exception: Missing unversioned deps in the normalized graph: ch.qos.logback:logback-classic
	at com.github.johnynek.bazel_deps.MakeDeps$$anonfun$resolve$2.apply(MakeDeps.scala:164)
	at com.github.johnynek.bazel_deps.MakeDeps$$anonfun$resolve$2.apply(MakeDeps.scala:131)
	at scala.util.Success.flatMap(Try.scala:231)
	at cats.instances.TryInstances$$anon$1.flatMap(try.scala:35)
	at cats.instances.TryInstances$$anon$1.flatMap(try.scala:14)
	at cats.FlatMap$Ops$class.flatMap(FlatMap.scala:21)
	at cats.FlatMap$ToFlatMapOps$$anon$2.flatMap(FlatMap.scala:21)
	at com.github.johnynek.bazel_deps.MakeDeps$.resolve(MakeDeps.scala:131)
	at com.github.johnynek.bazel_deps.MakeDeps$.runResolve(MakeDeps.scala:108)
	at com.github.johnynek.bazel_deps.MakeDeps$$anonfun$1.apply(MakeDeps.scala:37)
	at com.github.johnynek.bazel_deps.MakeDeps$$anonfun$1.apply(MakeDeps.scala:37)
	at scala.util.Success.flatMap(Try.scala:231)
	at com.github.johnynek.bazel_deps.MakeDeps$.apply(MakeDeps.scala:37)
	at com.github.johnynek.bazel_deps.ParseProject$.main(ParseProject.scala:17)
	at com.github.johnynek.bazel_deps.ParseProject.main(ParseProject.scala)
```

my dependencies.yaml looks something like this:

```
options:
  languages: [ "java" ]
  licenses: [ "notice" ]
  resolverType: "coursier"
  resolvers:
  - id: "mavencentral"
    type: "default"
    url: https://repo.maven.apache.org/maven2/
  thirdPartyDirectory: "third_party/jvm"
  buildHeader:
  - load("@io_bazel_rules_kotlin//kotlin:kotlin.bzl", "kt_jvm_import")
  - licenses(["notice"])

dependencies:

  ch.qos.logback:
    logback-classic:
      lang: kotlin
      vesion: "1.2.3"
```

I would have expected this to work - also I don't quite understand the error message. What does it mean?

**Comment by johnynek** [comment]
Is that jar really Kotlin?

In any case could this be a version of #220 ?

Lastly that error is actually just an assertion we have that everything declared winds up in the final graph. You could remove the assertion and see if things were fine yet it was the assertion failing.

**Comment by thundergolfer** [comment]
@Globegitter You spelt "version" incorrectly, that's why you're seeing that error. You've got `vesion:`

@johnynek I think this can be closed 👍

**Comment by johnynek** [comment]
Thanks. This is a problem with parsing as yaml with our current parser: it just silently ignores unexpected keys which means it doesn’t always see typos.
