### ISSUE TITLE
bazel-deps doesn't compile on Windows

### ISSUE THREAD

**Issue by redbaron** [johnynek/bazel-deps#231]
I am using `3fdaaa6de3ed8cf010a6b1713a04d55c4abb2592` of bazel-deps with 0.21.0 bazel on Windows 10 and it seems that use of `\` in paths on Windows plays a role in a following error:

```
C:\Users\mivanov\repos\bazel-deps> bazel run src/scala/com/github/johnynek/bazel_deps/parseproject_deploy.jar
INFO: Invocation ID: 84d868e2-7392-4dcd-8f21-0d6a431ac79b
DEBUG: C:/users/mivanov/_bazel_mivanov/nywkdake/external/bazel_tools/tools/cpp/lib_cc_configure.bzl:115:5:
Auto-Configuration Warning: 'PROGRAMFILES(X86)' environment variable is not set, using 'C:\Program Files (x86)' as default
INFO: Analysed target //src/scala/com/github/johnynek/bazel_deps:parseproject_deploy.jar (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: C:/users/mivanov/repos/bazel-deps/src/scala/com/github/johnynek/bazel_deps/BUILD:152:1: scala //src/scala/com/github/johnynek/bazel_deps:parseproject failed (Exit 1)
java.lang.RuntimeException: Resource File src\scala\com\github\johnynek\bazel_deps\templates\jar_artifact_backend.bzl is not under the specified strip prefix src/scala/com/github/johnynek/bazel_deps
        at io.bazel.rulesscala.scalac.ScalacProcessor.getResourcePath(ScalacProcessor.java:321)
        at io.bazel.rulesscala.scalac.ScalacProcessor.copyResources(ScalacProcessor.java:274)
        at io.bazel.rulesscala.scalac.ScalacProcessor.processRequest(ScalacProcessor.java:71)
        at io.bazel.rulesscala.worker.GenericWorker.run(GenericWorker.java:114)
        at io.bazel.rulesscala.scalac.ScalaCInvoker.main(ScalaCInvoker.java:41)
Target //src/scala/com/github/johnynek/bazel_deps:parseproject_deploy.jar failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 6.207s, Critical Path: 5.31s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
```

**Comment by johnynek** [comment]
Thanks for the bug report. I don’t have access to a windows machine so I’m not likely to get to this unfortunately.

I am happy to take a PR if you can figure it out and if TravisCI supports windows I’m happy to add windows to the CI so we don’t break it once it is fixed.

**Comment by redbaron** [comment]
It is a bug in rules_scala, filed https://github.com/bazelbuild/rules_scala/issues/655 , thanks for quick response though.
