### ISSUE TITLE
Bazel 0.25.0 compatibility

### ISSUE THREAD

**Issue by shs96c** [johnynek/bazel-deps#253]
When running under bazel 0.25.0, I get the following error:

```
ERROR: /private/var/tmp/_bazel_shs/70f0783c34451f509078ecb245a6a12c/external/io_bazel_rules_scala/third_party/unused_dependency_checker/src/main/BUILD:5:1: in scala_library_for_plugin_bootstrapping rule @io_bazel_rules_scala//third_party/unused_dependency_checker/src/main:unused_dependency_checker: 
Traceback (most recent call last):
	File "/private/var/tmp/_bazel_shs/70f0783c34451f509078ecb245a6a12c/external/io_bazel_rules_scala/third_party/unused_dependency_checker/src/main/BUILD", line 5
		scala_library_for_plugin_bootstrapping(name = 'unused_dependency_checker')
	File "/private/var/tmp/_bazel_shs/70f0783c34451f509078ecb245a6a12c/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 769, in scala_library_for_plugin_bootstrapping_impl
		_lib(ctx, scalac_provider.default_class..., <3 more arguments>)
	File "/private/var/tmp/_bazel_shs/70f0783c34451f509078ecb245a6a12c/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 689, in _lib
		_compile_or_empty(ctx, ctx.outputs.manifest, cjars, srcj..., <6 more arguments>)
	File "/private/var/tmp/_bazel_shs/70f0783c34451f509078ecb245a6a12c/external/io_bazel_rules_scala/scala/private/rule_impls.bzl", line 467, in _compile_or_empty
		java_common.run_ijar(ctx.actions, jar = ctx.outputs.jar, <2 more arguments>)
expected value of type 'JavaToolchainSkylarkApiProvider' for parameter 'java_toolchain', for call to method run_ijar(actions, jar, target_label = None, java_toolchain) of 'java_common'
```

It would seem that the version of the Scala rules need updating.

**Comment by johnynek** [comment]
Thanks for the bug report. Would you be willing to send a PR to bump the sha up?

**Comment by shs96c** [comment]
I'd love to, but it's proving tricky.

**Comment by johnynek** [comment]
@shs96c https://github.com/johnynek/bazel-deps/pull/254 this was already done. Have you tried master?
