### ISSUE TITLE
java.io.FileNotFoundException: /dependencies.yaml (No such file or directory)

### ISSUE THREAD

**Issue by maciejbak85** [johnynek/bazel-deps#268]
Hi,

Ive set system envs for directories:

> MY_PROJECT_DIR=/Users/maciejbak/workspace/moje/shapeless-bazel-zio-cats-playground
> BAZEL_DEPS=/Users/maciejbak/workspace/moje/bazel-deps

and I do like in readme:

> cd $BAZEL_DEPS
> 
> ➜  bazel-deps git:(master) bazel run //:parse generate -- --repo-root "$MY_PROJ_DIR" --sha-file 3rdparty/workspace.bzl --deps dependencies.yaml
> 
> DEBUG: Rule 'io_bazel_rules_scala' indicated that a canonical reproducible form can be obtained by modifying arguments shallow_since = "1560985393 -1000"
> DEBUG: Call stack for the definition of repository 'io_bazel_rules_scala' which is a git_repository (rule definition at /private/var/tmp/_bazel_maciejbak/4c0356e5b20b91e33074b9b3c0502286/external/bazel_tools/tools/build_defs/repo/git.bzl:195:18):
>  - /Users/maciejbak/workspace/moje/bazel-deps/WORKSPACE:7:1
> DEBUG: /private/var/tmp/_bazel_maciejbak/4c0356e5b20b91e33074b9b3c0502286/external/io_bazel_rules_scala/scala/scala_maven_import_external.bzl:59:9: 'jar_sha256' is deprecated. Please use 'artifact_sha256'
> INFO: Analyzed target //:parse (0 packages loaded, 0 targets configured).
> INFO: Found 1 target...
> Target //src/scala/com/github/johnynek/bazel_deps:parseproject up-to-date:
>   bazel-bin/src/scala/com/github/johnynek/bazel_deps/parseproject
>   bazel-bin/src/scala/com/github/johnynek/bazel_deps/parseproject.jar
> INFO: Elapsed time: 0.090s, Critical Path: 0.00s
> INFO: 0 processes.
> INFO: Build completed successfully, 1 total action
> INFO: Build completed successfully, 1 total action
> [main] ERROR MakeDeps - Failed to read dependencies.yaml
> java.io.FileNotFoundException: /dependencies.yaml (No such file or directory)
> 	at java.io.FileInputStream.open0(Native Method)
> 	at java.io.FileInputStream.open(FileInputStream.java:195)
> 	at java.io.FileInputStream.<init>(FileInputStream.java:138)
> 	at java.io.FileReader.<init>(FileReader.java:72)
> 	at com.github.johnynek.bazel_deps.Model$$anonfun$readFile$1.apply(DepsModel.scala:83)
> 	at com.github.johnynek.bazel_deps.Model$$anonfun$readFile$1.apply(DepsModel.scala:82)
> 	at scala.util.Try$.apply(Try.scala:192)
> 	at com.github.johnynek.bazel_deps.Model$.readFile(DepsModel.scala:82)
> 	at com.github.johnynek.bazel_deps.MakeDeps$.apply(MakeDeps.scala:18)
> 	at com.github.johnynek.bazel_deps.ParseProject$.main(ParseProject.scala:17)
> 	at com.github.johnynek.bazel_deps.ParseProject.main(ParseProject.scala)

but I have an error there..

file exists:

> 
>   bazel-deps git:(master) cat $MY_PROJECT_DIR/dependencies.yaml
> dependencies:
>   com.chuusai:
>     shapeless:
>       lang: scala
>       version: 2.3.3
>   joda-time:
>     joda-time:
>        lang: scala
>        version: 2.10.4%                                                                                                         

can someone help me with this ? thanks!

**Comment by johnynek** [comment]
since the error is `/dependencies.yaml` isn't found, it looks like your env-var is empty or something. it looks in the repo root to find the dependencies.yaml.
