### ISSUE TITLE
Simple dependencies.yaml failing

### ISSUE THREAD

**Issue by Jdban** [johnynek/bazel-deps#296]
This is the command that is running from the latest release .sh file (slightly modified from original)
```
$BAZEL_DEPS_PATH generate -r $REPO_ROOT -s 3rdparty/workspace.bzl -d dependencies.yaml
```

Here is everything in my `dependencies.yaml` at this point...

```
dependencies:
  com.google.firebase:
    firebase-admin:
      lang: java
      version: "6.12.2"
```

Here is the output/error: 

```
Updating bazel dependencies. This will take about five minutes.
[ForkJoinPool-1-worker-11] ERROR bazel_deps.CoursierResolver - not found: /Users/jasonbanich/.ivy2/local/io.grpc/grpc-core
[ForkJoinPool-1-worker-11] ERROR bazel_deps.CoursierResolver - No version found for [1.23.0,1.23.0] in https://repo.maven.apache.org/maven2/io/grpc/grpc-core/maven-metadata.xml
[main] ERROR MakeDeps - resolution and sha collection failed
java.lang.RuntimeException: Failed to resolve dependencies
	at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$buildGraph$1.apply(CoursierResolver.scala:278)
	at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$buildGraph$1.apply(CoursierResolver.scala:273)
	at scala.util.Success$$anonfun$map$1.apply(Try.scala:237)
	at scala.util.Try$.apply(Try.scala:192)
	at scala.util.Success.map(Try.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.Future$$anonfun$map$1.apply(Future.scala:237)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.pollAndExecAll(ForkJoinPool.java:1253)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1346)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

When I look at the url in the error where it says 'no version found for [1.23.0,1.23.0]' ([link](https://repo.maven.apache.org/maven2/io/grpc/grpc-core/maven-metadata.xml)), there does appear to be a 1.23.0 line `<version>1.23.0</version>`

I'm at a bit of a loss here. Does anyone have any insight?

**Comment by johnynek** [comment]
Usually this happens due to something unusual about the poms.

It could possibly be fixed by updating the dependency on coursier.

Sorry, I don't have time to run it down personally.

**Comment by Jdban** [comment]
So I was able to fix this by adding another resolver, but that resolver is just supposed to be a mirror of maven central. Any idea why that would fix it? Seems odd. I guess I can mark this closed though.

```
options:
  languages: [ "java" ]
  resolverType: "coursier"
  resolvers: 
    - id: "mavencentral"
      type: "default"
      url: https://repo.maven.apache.org/maven2/
    - id: "google-maven-central"
      type: "default"
      url: https://maven-central.storage-download.googleapis.com/maven2
```
