### ISSUE TITLE
Support for version ranges.

### ISSUE THREAD

**Issue by petroseskinder** [johnynek/bazel-deps#46]
This piggy backs off of issue #45.

When passed a maven coordinate with a range of dependencies, it seems that aether stops walking the graph at that node.

* Relevant [pom.xml] (https://search.maven.org/remotecontent?filepath=com/github/stefanbirkner/system-rules/1.14.0/system-rules-1.14.0.pom) file
* [Point](https://github.com/johnynek/bazel-deps/blob/master/src/scala/com/github/johnynek/bazel_deps/Resolver.scala#L167) in source code where it could break
* [Aether Visitor](https://github.com/johnynek/bazel-deps/blob/master/src/scala/com/github/johnynek/bazel_deps/Resolver.scala#L158) that may or may not support version ranges.

**Comment by aherrmann-da** [comment]
`bazel-deps` also fails on version ranges under the coursier resolver. The following `dependencies.yaml`

```
options:
  buildHeader:
    - "load(\"@io_bazel_rules_scala//scala:scala.bzl\", \"scala_library\")"
    - "load(\"@io_bazel_rules_scala//scala:scala_import.bzl\", \"scala_import\")"
  languages: [ "java", "scala:2.12.6" ]
  resolverType: "coursier"
dependencies:
  com.github.stefanbirkner:
    system-rules:
      lang: java
      version: "1.17.2"
```

Causes the following error

```
[main] ERROR MakeDeps - resolution and sha collection failed
java.lang.RuntimeException: no artifacts for junit:junit-dep:[4.9,) found
        at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$com$github$johnynek$bazel_deps$CoursierResolver$$lookup$1$1$$anonfun$apply$7$$anonfun$apply$9.apply(CoursierResolver.scala:188)
        at com.github.johnynek.bazel_deps.CoursierResolver$$anonfun$com$github$johnynek$bazel_deps$CoursierResolver$$lookup$1$1$$anonfun$apply$7$$anonfun$apply$9.apply(CoursierResolver.scala:186)
        at coursier.util.Task$$anonfun$flatMap$extension$1$$anonfun$apply$1.apply(Task.scala:10)
        at coursier.util.Task$$anonfun$flatMap$extension$1$$anonfun$apply$1.apply(Task.scala:10)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:253)
        at scala.concurrent.Future$$anonfun$flatMap$1.apply(Future.scala:251)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:36)
        at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:121)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by dan-ash** [comment]
+1

**Comment by johnynek** [comment]
very happy to take a PR here, but the right way to go may be to improve the integration with coursier and remove the aether backend completely.
