### ISSUE TITLE
The nonexistent optional dependency causes an exception

### ISSUE THREAD

**Issue by GinFungYJF** [johnynek/bazel-deps#88]
For example, I add the following to the dependencies.yaml.
```
org.springframework:
    spring-orm:
      lang: java
      version: "3.2.12.RELEASE"
```
And then run the tool to generate the files, I get the error:
```
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Exception in thread "main" org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.springframework:spring-orm:jar:3.2.12.RELEASE -> org.eclipse.persistence:org.eclipse.persistence.core:jar:1.0.1
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
	at com.github.johnynek.bazel_deps.Resolver.request(Resolver.scala:64)
	at com.github.johnynek.bazel_deps.Resolver.addToGraph(Resolver.scala:155)
	at com.github.johnynek.bazel_deps.Resolver$$anonfun$addAll$1.apply(Resolver.scala:151)
	at com.github.johnynek.bazel_deps.Resolver$$anonfun$addAll$1.apply(Resolver.scala:151)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.TraversableOnce$$anonfun$foldLeft$1.apply(TraversableOnce.scala:157)
	at scala.collection.Iterator$class.foreach(Iterator.scala:891)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1334)
	at scala.collection.MapLike$DefaultKeySet.foreach(MapLike.scala:174)
	at scala.collection.TraversableOnce$class.foldLeft(TraversableOnce.scala:157)
	at scala.collection.AbstractTraversable.foldLeft(Traversable.scala:104)
	at com.github.johnynek.bazel_deps.Resolver.addAll(Resolver.scala:151)
	at com.github.johnynek.bazel_deps.MakeDeps$.apply(MakeDeps.scala:45)
	at com.github.johnynek.bazel_deps.ParseProject$.main(ParseProject.scala:11)
	at com.github.johnynek.bazel_deps.ParseProject.main(ParseProject.scala)
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for org.eclipse.persistence:org.eclipse.persistence.core:jar:1.0.1
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:329)
	at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:217)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:535)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:519)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
	at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
	... 16 more
```
The artifact `org.eclipse.persistence:org.eclipse.persistence.core:jar:1.0.1` is an optional dependency of the artifact `org.springframework:spring-orm:jar:3.2.12.RELEASE`, but `org.eclipse.persistence:org.eclipse.persistence.core:jar:1.0.1` is not in our private repositories or even in "http://repo.maven.apache.org/maven2". Any suggestion or workaround?

**Comment by promiseofcake** [comment]
Have you tried the `exclude` option?

```
  org.apache.spark:
    spark:
      exclude: 
        - "org.xerial.snappy:snappy-java"
      lang: java
      modules: [ "core_2.11", "sql_2.11" ]
      version: "2.2.0"
```

**Comment by GinFungYJF** [comment]
@promiseofcake I' ve try, but it didn't work.

**Comment by promiseofcake** [comment]
This `deps.yaml` worked for me -- have you updated to the latest version of the tool? Do you have something else that is causing that collision?

```
options:
  buildHeader: [ "load(\"@io_bazel_rules_scala//scala:scala.bzl\", \"scala_library\")" ]
  languages: [ "java", "scala:2.11.8" ]
  resolvers: 
    - id: "mavencentral"
      type: "default"
      url: https://repo.maven.apache.org/maven2/
  transitivity: exports
  versionConflictPolicy: highest

dependencies:
  org.springframework:
    spring-orm:
      lang: java
      version: "3.2.12.RELEASE"
```

**Comment by GinFungYJF** [comment]
Thanks! I think the exception was caused by the proxy issues. The default resolver I wrote is our private repository. I changed the id of it to `central` as well as added a new resolver which is our company's public repository. It finally worked.
